version: "3"

services:
  backend:
    build: ./backend
    command: npm run start
    restart: "always"
    ports:
      - "4000:4000"
    depends_on: 
      - timelogs
    networks:
      - webnet
  timelogs: 
    build: ./backend/services/timelogs
    command: npm run start
    restart: "always"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - "4001:4001"
    networks:
      - webnet
  app: 
    build: ./app
    command: npm start
    ports:
      - "3000:3000"
    links:
      - backend
    restart: "always"
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules/
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - webnet

networks:
  webnet: